import { useEffect, useState, type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { formatWon } from '../data'
import { supabase } from '../lib/supabase'
import { useAppStore } from '../store/AppStore'

type PaymentSetting = { bank_name: string; account_number: string; account_holder: string; deposit_deadline_hours: number }
type BankOrder = { id: string; order_no: string; amount: number; depositor_name: string; payment_deadline: string; bank_snapshot: PaymentSetting }

export function Checkout() {
  const { t, i18n } = useTranslation(); const { user, profile } = useAuth(); const { cart, products, clearCart } = useAppStore(); const [setting, setSetting] = useState<PaymentSetting | null>(null); const [settingLoaded, setSettingLoaded] = useState(false); const [depositor, setDepositor] = useState(profile?.display_name ?? ''); const [order, setOrder] = useState<BankOrder | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [copied, setCopied] = useState(false)
  const lines = cart.flatMap(item => { const product = products.find(p => p.id === item.productId); const variant = product?.variants.find(v => v.id === item.variantId); return product && variant ? [{ sku: product.sku, name: product.name, nameKo: product.nameKo, option: `${variant.color} · ${variant.size}`, quantity: item.quantity, price: product.price, image: product.image }] : [] })
  const estimated = lines.reduce((sum, line) => sum + line.price * line.quantity, 0)
  useEffect(() => { if (!supabase) { setSettingLoaded(true); return }; void supabase.from('payment_settings').select('bank_name,account_number,account_holder,deposit_deadline_hours').eq('active', true).maybeSingle().then(({ data }) => { setSetting(data as PaymentSetting | null); setSettingLoaded(true) }) }, [])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!supabase || !user || !lines.length) return; setBusy(true); setMessage(''); const items = lines.map(line => ({ sku: line.sku, option: line.option, quantity: line.quantity })); const { data, error } = await supabase.rpc('create_bank_transfer_order', { payer_name: depositor, order_items: items }); if (error) { setBusy(false); setMessage(error.message); return }; const created = data as BankOrder; setOrder(created); clearCart(); const { error: notifyError } = await supabase.functions.invoke('notify-bank-order', { body: { order_id: created.id } }); if (notifyError) console.warn('Telegram notification pending:', notifyError.message); setBusy(false) }
  const copy = async () => { if (!setting) return; await navigator.clipboard.writeText(setting.account_number); setCopied(true); window.setTimeout(() => setCopied(false), 1500) }
  if (!user) return <main className="checkout-gate"><p>{t('checkout.login')}</p><Link to="/account">LOGIN →</Link></main>
  if (order) { const bank = order.bank_snapshot; return <main className="checkout-complete"><section><p>ORDER {order.order_no}</p><h1>{t('checkout.complete')}</h1><span>{t('checkout.instruction', { deadline: new Date(order.payment_deadline).toLocaleString(i18n.language), amount: formatWon(order.amount) })}</span><div className="transfer-ticket"><p>{bank.bank_name}</p><strong>{bank.account_number}</strong><span>{bank.account_holder} · {order.depositor_name}</span><b>{formatWon(order.amount)}</b><button onClick={copy}>{copied ? t('checkout.copied') : t('checkout.accountCopy')}</button></div><Link to="/account?tab=orders">{t('nav.orders')} →</Link></section></main> }
  return <main className="checkout-page"><section className="checkout-form"><p>{t('checkout.eyebrow')}</p><h1>{t('checkout.title')}</h1>{setting ? <div className="bank-preview"><span>{t('checkout.bank')}</span><strong>{setting.bank_name} · {setting.account_number}</strong><em>{setting.account_holder}</em></div> : <p>{settingLoaded ? t('checkout.unavailable') : t('common.loading')}</p>}<form onSubmit={submit}><label>{t('checkout.depositor')}<input value={depositor} onChange={e => setDepositor(e.target.value)} required /></label><p>{t('checkout.depositorHelp')}</p><button className="ink-button" disabled={busy || !setting}>{busy ? t('common.loading') : t('checkout.order')}</button><span>{message}</span></form></section><aside className="checkout-summary"><p>{t('checkout.summary')}</p>{lines.map(line => <article key={`${line.sku}-${line.option}`}><img src={line.image} alt="" /><div><h3>{i18n.language === 'en' ? line.name : line.nameKo}</h3><span>{line.option} · {line.quantity}</span></div><strong>{formatWon(line.price * line.quantity)}</strong></article>)}<div><span>{t('checkout.amount')}</span><strong>{formatWon(estimated)}</strong></div></aside></main>
}
