import { useEffect, useState, type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { supabase } from '../lib/supabase'

type RequestRow = { id: string; product_name: string; description: string; status: string; created_at: string }

export function Mending() {
  const { t } = useTranslation(); const { user } = useAuth(); const [product, setProduct] = useState(''); const [description, setDescription] = useState(''); const [files, setFiles] = useState<File[]>([]); const [requests, setRequests] = useState<RequestRow[]>([]); const [message, setMessage] = useState('')
  useEffect(() => { if (!supabase || !user) return; void supabase.from('mending_requests').select('id,product_name,description,status,created_at').order('created_at', { ascending: false }).then(({ data }) => setRequests((data ?? []) as RequestRow[])) }, [user])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!supabase || !user) return; setMessage(String(t('common.loading'))); const uploads = await Promise.all(files.map(async file => { const storagePath = `${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const { error } = await supabase!.storage.from('mending-images').upload(storagePath, file); return error ? null : storagePath })); const { data, error } = await supabase.from('mending_requests').insert({ product_name: product, description, images: uploads.filter(Boolean) }).select('id,product_name,description,status,created_at').single(); if (error) { setMessage(error.message); return }; setRequests(current => [data as RequestRow, ...current]); setProduct(''); setDescription(''); setFiles([]); setMessage(String(t('mending.promise'))) }
  const steps = t('mending.steps', { returnObjects: true }) as string[]
  return <main className="mending-page"><section className="mending-hero"><div><p>{t('mending.eyebrow')}</p><h1>{String(t('mending.title')).split('\n').map(line => <span key={line}>{line}</span>)}</h1><em>{t('mending.intro')}</em><strong>{t('mending.promise')}</strong></div><img src="/images/detail-chevron.jpg" alt="Garment mending detail" /></section><section className="mending-steps">{steps.map((step, i) => <div key={step}><span>{String(i + 1).padStart(2, '0')}</span><p>{step}</p></div>)}</section><section className="mending-workspace"><div className="mending-copy"><p>REPAIR REQUEST</p><h2>{t('mending.request')}</h2><span>작은 스티치부터 부자재 교체까지, 제품을 확인한 뒤 가장 자연스러운 방법을 제안합니다.</span></div>{user ? <form onSubmit={submit}><label>{t('mending.product')}<select value={product} onChange={e => setProduct(e.target.value)} required><option value="">—</option><option>Work Jacket</option><option>Field Jacket</option><option>Leather Jacket</option><option>Fleece</option><option>Trousers</option><option>Bag</option></select></label><label>{t('mending.detail')}<textarea value={description} onChange={e => setDescription(e.target.value)} required /></label><label>{t('mending.photos')}<input type="file" accept="image/*" multiple onChange={e => setFiles(Array.from(e.target.files ?? []).slice(0, 5))} /><small>{files.length}/5</small></label><span>{message}</span><button className="ink-button">{t('mending.submit')}</button></form> : <Link className="mending-login" to="/account">{t('mending.login')} →</Link>}</section>{user ? <section className="mending-history"><header><p>MENDING ARCHIVE</p><h2>{t('mending.my')}</h2></header>{requests.length ? requests.map(row => <article key={row.id}><time>{new Date(row.created_at).toLocaleDateString()}</time><h3>{row.product_name}</h3><p>{row.description}</p><span>{row.status.toUpperCase()}</span></article>) : <p>{t('common.empty')}</p>}</section> : null}</main>
}
