import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  ko: { translation: {
    nav: { shop: '쇼핑', find: '발견', mending: '수선', login: '로그인', logout: '로그아웃', bag: '장바구니', account: '내 계정', orders: '주문 내역', points: '적립금', reviews: '리뷰', inquiries: 'Q&A', notice: '공지사항', admin: '스토어 오피스' },
    home: { eyebrow: 'ΦΙΛΊΑ · PHILIA · 필리아', title: 'Clothes that stay,\nthe way love stays.', subtitle: '따뜻한 사랑처럼, 오래 머무르는 옷.', shop: '컬렉션 1 보기', findTitle: '발견', findCopy: '한 벌에 세 가지 흔적. 여섯 개를 모두 드러내지 않습니다.', mendingTitle: 'Clothes that stay,\nthe way love stays.', mendingCopy: '옷은 시간이 지날수록 당신의 것이 됩니다. 필리아의 모든 옷은 오래 입기 위한 기본 수선을 무료로 제공합니다.' },
    shop: { title: '컬렉션 1', subtitle: '오래 머물도록 만든 여섯 가지 옷.', all: '전체', view: '상품 보기', close: '가까이 보기' },
    product: { color: '색상', size: '사이즈', sizeGuide: '사이즈 가이드', add: '장바구니에 담기', shipping: '2일 이내 출고', mended: '기본 수선 무료', material: '소재', signatures: '세 가지 흔적', care: '관리', measurements: '실측', related: '함께 입기', vat: '부가세 포함', materialCopy: '천연 소재의 표정과 시간이 만든 변화를 존중합니다.', careCopy: '찬물 단독 세탁 또는 전문 클리닝을 권장합니다.', measurementsCopy: '상세 실측은 상품마다 1–2cm의 편차가 있을 수 있습니다.' },
    cart: { empty: '아직 담긴 옷이 없습니다.', remove: '삭제', subtotal: '상품 합계', shipping: '배송비는 결제 단계에서 계산됩니다.', checkout: '결제하기' },
    footer: { idea: '필리아의 생각', signatures: '여섯 가지 흔적', fit: '사이즈와 핏', shipping: '배송 안내', returns: '교환·반품·환불', newsletter: '세일과 카운트다운 대신, 새 볼륨과 수선 데스크의 소식을 전합니다.', join: '구독' },
    legal: { privacy: '개인정보처리방침', refund: '교환·환불 정책', business: '상호', representative: '대표자', registration: '사업자등록번호', businessType: '업태·종목', businessTypeValue: '의류 제조업 · 전자상거래 소매업', hosting: '호스팅 제공자', address: '사업장 소재지', addressValue: '서울특별시 중랑구 망우로 2, 1층 103호(망우동, 일흥교통(주))', contact: '고객·개인정보 문의', links: '법적 고지', effective: '시행일', contents: '목차' },
    account: { eyebrow: 'PHILIA 계정', introTitle: '당신의 옷과 기록을\n한곳에 모았습니다.', intro: '주문과 수선의 기록을 한 곳에서 관리합니다.', login: '로그인', join: '가입', name: '이름', email: '이메일', password: '비밀번호', wait: '잠시만 기다려 주세요…', sendCode: '인증번호 받기', backEmail: '이메일 다시 입력', verification: '이메일 인증', enterCode: '인증번호를 입력해 주세요.', codeSent: '{{email}}로 보낸 일회용 인증번호입니다.', verify: '인증 완료', resend: '인증번호 다시 받기', secure: '이메일 인증번호를 통해 안전하게 가입합니다.', welcome: '{{name}}님,\n다시 만나 반갑습니다.', profile: '회원정보', orderHistory: '주문내역', points: '적립금', myReviews: '나의 리뷰', myInquiries: '나의 문의', greeting: '회원 공간', noOrders: '아직 주문 내역이 없습니다.', noReviews: '작성한 리뷰가 없습니다.', loading: '불러오는 중…' },
    community: { title: '오래 남는 이야기.', intro: '입은 사람의 시간과 궁금한 마음, 필리아의 소식을 나눕니다.', reviews: '리뷰', inquiry: '문의', notice: '공지', archive: '리뷰 아카이브', writeReview: '리뷰 작성', ask: '문의하기', signToWrite: '로그인 후 작성', signToAsk: '로그인 후 문의', noInquiry: '공개된 문의가 없습니다.', noNotice: '등록된 공지가 없습니다.', answered: '답변완료', waiting: '답변대기', helpful: '도움돼요', comments: '댓글', close: '닫기' },
    find: { eyebrow: 'THE FIND · 발견', title: '보이는 것보다\n오래 남는 것.', intro: '필리아의 옷에는 밖으로 드러내기보다 입는 사람만 발견하도록 남겨둔 흔적이 있습니다.', archive: '여섯 가지 시그니처', stories: '옷의 안쪽에서 시작된 이야기', inspect: '이야기 보기' },
    mending: { eyebrow: 'MENDING DESK · 수선 데스크', title: '계속 입기 위한\n조용한 약속.', intro: '오래 입는 동안 생긴 흔적을 보내주세요. 수선 가능 여부와 방법을 확인해 안내합니다.', promise: '기본 수선은 언제나 무료입니다.', steps: ['온라인 접수', '상태 확인', '제품 발송', '수선 및 반환'], request: '수선 접수하기', my: '내 수선 현황', product: '제품명', detail: '수선이 필요한 부분', photos: '사진', submit: '수선 요청 보내기', login: '로그인 후 수선 접수' },
    checkout: { eyebrow: 'PAYMENT · 결제', title: '주문을 확인해 주세요.', customerInfo: '고객 정보', shippingInfo: '배송지 정보', email: '이메일', recipient: '받으시는 분', phone: '휴대전화', postalCode: '우편번호', findAddress: '주소 찾기', address: '기본 주소', addressDetail: '상세 주소', deliveryMessage: '배송 메시지', deliveryPlaceholder: '문 앞에 놓아주세요. (선택)', saveProfile: '이 배송지를 회원정보에 저장하고 다음 주문에서 불러옵니다.', addressSearchError: '주소 검색을 불러오지 못했습니다. 직접 입력하거나 잠시 후 다시 시도해 주세요.', shippingRequired: '받으시는 분, 연락처, 우편번호와 주소를 모두 입력해 주세요.', agreementRequired: '결제 진행 동의가 필요합니다.', method: '결제 수단', card: '카드 결제', onlyToss: '안전한 토스페이먼츠 결제', summary: '주문 요약', subtotal: '상품 금액', shippingFee: '배송비', free: '무료', freeShippingHelp: '{{amount}} 이상 구매 시 무료배송', amount: '총 결제예정 금액', login: '주문하려면 로그인해 주세요.', testNotice: '토스페이먼츠 테스트 환경입니다. 실제 금액은 청구되지 않습니다.', agreement: '구매 조건과 개인정보 제공 내용을 확인했으며 결제 진행에 동의합니다.', tossPay: '{{amount}} 테스트 결제하기', testHelp: '결제창에서 토스페이먼츠 테스트 카드 결제를 진행합니다.', tossConfirming: '결제를 승인하고 있습니다.', tossConfirmingHelp: '창을 닫거나 뒤로 이동하지 마세요.', tossComplete: '테스트 결제가 완료되었습니다.', testCharge: '테스트 결제 · 실제 청구 없음', tossFailed: '결제를 완료하지 못했습니다.', tossFailedHelp: '결제 정보를 확인하고 다시 시도해 주세요.', tossCancelled: '결제가 취소되었습니다.', tossInvalid: '결제 승인 정보가 올바르지 않습니다.', retry: '결제 다시 시도', receipt: '테스트 영수증' },
    common: { save: '저장', close: '닫기', cancel: '취소', loading: '불러오는 중…', empty: '내역이 없습니다.', submit: '등록', status: '상태', date: '날짜', edit: '수정', manage: '관리' },
    admin: { overview: '개요', products: '상품', inventory: '재고', finance: '손익 · 세금', orders: 'Toss 결제·주문', editorial: '발견 · 수선', content: '콘텐츠', users: '사용자 관리', settings: '설정' },
    adminUsers: { title: '사용자 관리', description: '회원과 운영자의 접근 권한을 관리합니다.', addTitle: '관리자 이메일 추가', addDescription: '가입된 회원은 즉시 승격되고, 가입 전 이메일은 역할이 예약됩니다.', role: '역할', add: '권한 추가', member: '회원', joined: '가입일', pending: '가입 대기 권한', confirmRole: '{{email}}의 역할을 {{role}}로 변경할까요?', updated: '역할을 변경했습니다.', promoted: '가입된 회원의 역할을 변경했습니다.', reserved: '해당 이메일이 가입하면 역할이 자동 적용됩니다.' }
  } },
  en: { translation: {
    nav: { shop: 'Shop', find: 'The Find', mending: 'Mending', login: 'Login', logout: 'Logout', bag: 'Bag', account: 'My account', orders: 'Orders', points: 'Points', reviews: 'Reviews', inquiries: 'Q&A', notice: 'Notice', admin: 'Store office' },
    home: { eyebrow: 'ΦΙΛΊΑ · PHILIA', title: 'Clothes that stay,\nthe way love stays.', subtitle: 'Warm as love, made to stay.', shop: 'Shop Collection 1', findTitle: 'The find', findCopy: 'Three signatures per piece, never all six. None of them on the outside.', mendingTitle: 'Clothes that stay,\nthe way love stays.', mendingCopy: 'Clothes become yours with time. Every PHILIA piece includes complimentary essential mending, made to help it stay.' },
    shop: { title: 'Collection 1', subtitle: 'Six pieces made to stay.', all: 'All', view: 'View piece', close: 'See a piece up close' },
    product: { color: 'Colourway', size: 'Size', sizeGuide: 'Size & fit guide', add: 'Add to bag', shipping: 'Ships in 2 days', mended: 'Mended free', material: 'Material', signatures: 'The find — three signatures', care: 'How it ages', measurements: 'Measurements', related: 'Layer it with', vat: 'Incl. VAT', materialCopy: 'We honour the character of natural materials and the changes made by time.', careCopy: 'Wash separately in cold water or use a specialist cleaner.', measurementsCopy: 'Individual garments may vary by 1–2 cm.' },
    cart: { empty: 'Your bag is waiting.', remove: 'Remove', subtotal: 'Subtotal', shipping: 'Shipping is calculated at checkout.', checkout: 'Checkout' },
    footer: { idea: 'The idea', signatures: 'Six signatures', fit: 'Size & fit', shipping: 'Shipping', returns: 'Returns & refunds', newsletter: 'No sales or countdowns—only notes on new volumes and the mending desk.', join: 'Join' },
    legal: { privacy: 'Privacy policy', refund: 'Returns & refunds', business: 'Business', representative: 'Representative', registration: 'Business registration no.', businessType: 'Business activities', businessTypeValue: 'Apparel manufacturing · Online retail', hosting: 'Hosting provider', address: 'Business address', addressValue: 'Unit 103, 1F, 2 Mangu-ro, Jungnang-gu, Seoul, Republic of Korea', contact: 'Customer & privacy contact', links: 'Legal notices', effective: 'Effective', contents: 'Contents' },
    account: { eyebrow: 'PHILIA ACCOUNT', introTitle: 'Your pieces,\nkept together.', intro: 'Manage your orders and mending history in one place.', login: 'Login', join: 'Join', name: 'Name', email: 'Email', password: 'Password', wait: 'Please wait…', sendCode: 'Send verification code', backEmail: 'Change email', verification: 'Email verification', enterCode: 'Enter your verification code.', codeSent: 'We sent a one-time code to {{email}}.', verify: 'Verify', resend: 'Send a new code', secure: 'Join securely with a one-time email code.', welcome: 'Welcome back,\n{{name}}.', profile: 'Profile', orderHistory: 'Orders', points: 'Points', myReviews: 'My reviews', myInquiries: 'My Q&A', greeting: 'Member space', noOrders: 'You have no orders yet.', noReviews: 'You have not written a review yet.', loading: 'Loading…' },
    community: { title: 'Stories that stay.', intro: 'Notes from wearing, thoughtful questions, and news from PHILIA.', reviews: 'Reviews', inquiry: 'Q&A', notice: 'Notice', archive: 'Review archive', writeReview: 'Write a review', ask: 'Ask PHILIA', signToWrite: 'Sign in to write', signToAsk: 'Sign in to ask', noInquiry: 'No public questions yet.', noNotice: 'No notices yet.', answered: 'Answered', waiting: 'Waiting', helpful: 'Helpful', comments: 'Comments', close: 'Close' },
    find: { eyebrow: 'THE FIND', title: 'What remains\nbeyond sight.', intro: 'PHILIA garments hold quiet signatures, placed for the wearer to discover rather than for the outside to see.', archive: 'Six signatures', stories: 'Stories that begin on the inside', inspect: 'Read the story' },
    mending: { eyebrow: 'MENDING DESK', title: 'A quiet promise\nto keep it going.', intro: 'Tell us about the marks left by wear. We will review the piece and guide you through what can be repaired.', promise: 'Essential mending is always complimentary.', steps: ['Request online', 'Assessment', 'Send the piece', 'Mend & return'], request: 'Request mending', my: 'My repairs', product: 'Product name', detail: 'What needs mending', photos: 'Photos', submit: 'Send request', login: 'Sign in to request mending' },
    checkout: { eyebrow: 'PAYMENT', title: 'Review your order.', customerInfo: 'Customer information', shippingInfo: 'Shipping information', email: 'Email', recipient: 'Recipient', phone: 'Mobile phone', postalCode: 'Postal code', findAddress: 'Find address', address: 'Address', addressDetail: 'Apartment, suite, etc.', deliveryMessage: 'Delivery note', deliveryPlaceholder: 'Leave at the door. (Optional)', saveProfile: 'Save this address to my profile for my next order.', addressSearchError: 'Address search could not be loaded. Enter the address manually or try again.', shippingRequired: 'Enter the recipient, phone number, postal code, and address.', agreementRequired: 'Please agree before continuing to payment.', method: 'Payment method', card: 'Card payment', onlyToss: 'Secure checkout by Toss Payments', summary: 'Order summary', subtotal: 'Subtotal', shippingFee: 'Shipping', free: 'Free', freeShippingHelp: 'Free shipping on orders over {{amount}}', amount: 'Total due', login: 'Please sign in to place an order.', testNotice: 'This is the Toss Payments test environment. No real charge will be made.', agreement: 'I have reviewed the purchase terms and consent to the payment and data processing.', tossPay: 'Test pay {{amount}}', testHelp: 'Continue with a Toss Payments test card payment.', tossConfirming: 'Confirming your payment.', tossConfirmingHelp: 'Please do not close this window or go back.', tossComplete: 'Test payment complete.', testCharge: 'Test payment · No real charge', tossFailed: 'We could not complete the payment.', tossFailedHelp: 'Review the payment details and try again.', tossCancelled: 'Payment cancelled.', tossInvalid: 'The payment approval information is invalid.', retry: 'Try payment again', receipt: 'Test receipt' },
    common: { save: 'Save', close: 'Close', cancel: 'Cancel', loading: 'Loading…', empty: 'Nothing here yet.', submit: 'Submit', status: 'Status', date: 'Date', edit: 'Edit', manage: 'Manage' },
    admin: { overview: 'Overview', products: 'Products', inventory: 'Inventory', finance: 'Profit · Tax', orders: 'Toss payments · Orders', editorial: 'Find · Mending', content: 'Content', users: 'Users', settings: 'Settings' },
    adminUsers: { title: 'User management', description: 'Manage member and operator access.', addTitle: 'Add an operator by email', addDescription: 'Existing members are promoted now; new emails receive the role when they sign up.', role: 'Role', add: 'Grant access', member: 'Member', joined: 'Joined', pending: 'Pending role grants', confirmRole: 'Change {{email}} to {{role}}?', updated: 'Role updated.', promoted: 'The existing member was promoted.', reserved: 'The role will be applied when this email signs up.' }
  } },
}

const stored = localStorage.getItem('philia-language')
const initialLanguage = stored === 'ko' ? 'ko' : 'en'
void i18n.use(initReactI18next).init({ resources, lng: initialLanguage, fallbackLng: 'en', interpolation: { escapeValue: false } })
document.documentElement.lang = initialLanguage

export const setLanguage = async (language: 'ko' | 'en') => { localStorage.setItem('philia-language', language); document.documentElement.lang = language; await i18n.changeLanguage(language) }
export default i18n
